apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  POSTGRES_USER: demo
  POSTGRES_PASSWORD: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: database-config
          env:
              # Overwrites the values from database-config
              # So we can apply pre-start migrations
            - name: PGHOST
              value: ""
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
